# Generated by Django 5.1.1 on 2024-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('sets', models.JSONField(blank=True, null=True)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
