# Generated by Django 5.1.1 on 2024-09-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_series_delete_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='sets',
        ),
    ]
