# Generated by Django 5.1.1 on 2024-09-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_series_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='release_date',
        ),
    ]
