# Generated by Django 5.1.1 on 2024-09-22 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_series_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('cost', models.JSONField()),
                ('damage', models.CharField(max_length=255)),
                ('convertedEnergyCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('set_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('set_symbol', models.ImageField(blank=True, null=True, upload_to='')),
                ('card_count_first_edition', models.IntegerField()),
                ('card_count_holo', models.IntegerField()),
                ('card_count_normal', models.IntegerField()),
                ('card_count_official', models.IntegerField()),
                ('card_count_reverse', models.IntegerField()),
                ('card_count_total', models.IntegerField()),
                ('from_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.series')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hp', models.IntegerField()),
                ('evolves_from', models.CharField(max_length=75, null=True)),
                ('weaknesses', models.JSONField()),
                ('retreat_cost', models.JSONField()),
                ('convert_retreat_cost', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('illustrator', models.CharField(max_length=255)),
                ('rarity', models.CharField(max_length=255)),
                ('flavor_text', models.CharField(max_length=255)),
                ('national_pokedex_numbers', models.JSONField()),
                ('legalities', models.JSONField()),
                ('small_image', models.ImageField(null=True, upload_to='')),
                ('large_image', models.ImageField(null=True, upload_to='')),
                ('categoty', models.CharField(max_length=255)),
                ('local_id', models.IntegerField()),
                ('variant_first_edition', models.BooleanField()),
                ('variant_holo', models.BooleanField()),
                ('variant_normal', models.BooleanField()),
                ('variant_reverse', models.BooleanField()),
                ('variant_w_promo', models.BooleanField()),
                ('abilities', models.ManyToManyField(to='api.ability')),
                ('attacks', models.ManyToManyField(to='api.attack')),
                ('from_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.set')),
                ('subtypes', models.ManyToManyField(to='api.subtype')),
                ('supertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supertype')),
                ('types', models.ManyToManyField(to='api.typetype')),
            ],
        ),
    ]
