# Generated by Django 5.1.1 on 2024-09-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ability_attack_subtype_supertype_typetype_set_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='categoty',
        ),
        migrations.RemoveField(
            model_name='card',
            name='local_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='variant_first_edition',
        ),
        migrations.RemoveField(
            model_name='card',
            name='variant_holo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='variant_normal',
        ),
        migrations.RemoveField(
            model_name='card',
            name='variant_reverse',
        ),
        migrations.RemoveField(
            model_name='card',
            name='variant_w_promo',
        ),
    ]
