# Generated by Django 5.1.1 on 2024-09-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_card_categoty_remove_card_local_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='TypeType',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='card_count_official',
            new_name='card_count_printed_total',
        ),
        migrations.RemoveField(
            model_name='set',
            name='card_count_first_edition',
        ),
        migrations.RemoveField(
            model_name='set',
            name='card_count_holo',
        ),
        migrations.RemoveField(
            model_name='set',
            name='card_count_normal',
        ),
        migrations.RemoveField(
            model_name='set',
            name='card_count_reverse',
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rarity'),
        ),
    ]
