# Generated by Django 5.1.1 on 2024-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rarity_rename_typetype_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='large_image',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='small_image',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='logo',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_logo',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_symbol',
            field=models.FilePathField(null=True),
        ),
    ]
